# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GapDetectionDialog
                                 A QGIS plugin
 recognize gaps in hop growth
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-25
        git sha              : $Format:%H$
        copyright            : (C) 2022 by Josef Kořínek
        email                : josefkorinek@bezobsahu.cz
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import os
import sys

from qgis.PyQt import uic
from qgis.PyQt import QtWidgets

#for reading path of project
from qgis.core import QgsProject

def  
# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'gap_detection_dialog_base.ui'))


class GapDetectionDialog(QtWidgets.QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        """Constructor."""
        super(GapDetectionDialog, self).__init__(parent)
        # Set up the user interface from Designer through FORM_CLASS.
        # After self.setupUi() you can access any designer object by doing
        # self.<objectname>, and you can use autoconnect slots - see
        # http://qt-project.org/doc/qt-4.8/designer-using-a-ui-file.html
        # #widgets-and-dialogs-with-auto-connect
        self.setupUi(self)
        #Pushbutons
        self.pbHello.clicked.connect(self.pbHelloClicked)
        self.pbLoadFile.clicked.connect(self.LoadFile)

    def pbHelloClicked(self):
        print('heloooooo')
        text = self.cbLayers.currentText
        print(text)
        pointLayer.write = "nejake souradnice 00 111"
        pointLayer.close()
        print(pathOfProject)

    def LoadFile (self):

       
        pathOfProject = QgsProject.instance().readPath("./")
        nameOfFile="layerWithPoints"
        completeName= pathOfProject+"/"+nameOfFile+".txt"
        print(completeName)
        pointLayer = open(completeName,"w") 
        
        
       


        




