# -*- coding: utf-8 -*-
"""
/***************************************************************************
 ga
                                 A QGIS plugin
 dasas
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2023-02-27
        copyright            : (C) 2023 by jose
        email                : koren
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load ga class from file ga.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .sdfw import ga
    return ga(iface)
